# Generated by Django 3.2 on 2023-05-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='is_bookmark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_valid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='parent_resource_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='user_account_id',
            field=models.CharField(max_length=10),
        ),
    ]
