# Generated by Django 3.2 on 2023-05-23 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230518_1159'),
        ('file', '0002_auto_20230523_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='parent_resource_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='user_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
