# Generated by Django 3.2 on 2023-05-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('accountType', models.CharField(choices=[('RE', 'regular'), ('GU', 'guest')], default='RE', max_length=2)),
                ('url', models.URLField(null=True)),
                ('expirationTime', models.IntegerField(null=True)),
            ],
        ),
    ]
