# Generated by Django 3.2 on 2023-05-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230504_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_type',
            new_name='accountType',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='expiration_time',
            new_name='expirationTime',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
