# Generated by Django 3.2 on 2023-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('accountType', models.CharField(choices=[('RE', 'regular'), ('GU', 'guest')], max_length=2)),
                ('expirationTime', models.IntegerField(null=True)),
            ],
        ),
    ]
