# Generated by Django 3.2 on 2023-06-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_img_b64', models.TextField()),
                ('url_origin', models.URLField()),
                ('url', models.URLField()),
                ('code', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
